# Project 3

In this project, you will perform a logistic regression on the admissions data we've been working with in projects 1 and 2.

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
import pylab as pl
import numpy as np
from sklearn.linear_model import LogisticRegression

In [4]:
df_raw = pd.read_csv("../assets/admissions.csv")
df = df_raw.dropna() 
print df.head()

   admit    gre   gpa  prestige
0      0  380.0  3.61       3.0
1      1  660.0  3.67       3.0
2      1  800.0  4.00       1.0
3      1  640.0  3.19       4.0
4      0  520.0  2.93       4.0


## Part 1. Frequency Tables

#### 1. Let's create a frequency table of our variables

In [70]:
# frequency table for prestige and whether or not someone was admitted
#aka crosstabs
#two-way tables are called contingency tables

In [5]:
admit_prestige = pd.crosstab(index=df['admit'],
                            columns=df['prestige'])
admit_prestige

prestige  1.0  2.0  3.0  4.0
admit                       
0          28   95   93   55
1          33   53   28   12

## Part 2. Return of dummy variables

#### 2.1 Create class or dummy variables for prestige 

In [6]:
prestige_dummy = pd.get_dummies(df.prestige, prefix='prestige')

prestige_dummy.head()

prestige_1.0  prestige_2.0  prestige_3.0  prestige_4.0
0           0.0           0.0           1.0           0.0
1           0.0           0.0           1.0           0.0
2           1.0           0.0           0.0           0.0
3           0.0           0.0           0.0           1.0
4           0.0           0.0           0.0           1.0

#### 2.2 When modeling our class variables, how many do we need? 



Answer: Just 3, since you can then infer the 4th after seeing the values for 3. This will also prevent multicollinearity by removing one of the dummmy variable columns.

## Part 3. Hand calculating odds ratios

Develop your intuition about expected outcomes by hand calculating odds ratios.

In [7]:
cols_to_keep = ['admit', 'gre', 'gpa']
handCalc = df[cols_to_keep].join(prestige_dummy.ix[:, 'prestige_1':])
print handCalc.head()

   admit    gre   gpa  prestige_1.0  prestige_2.0  prestige_3.0  prestige_4.0
0      0  380.0  3.61           0.0           0.0           1.0           0.0
1      1  660.0  3.67           0.0           0.0           1.0           0.0
2      1  800.0  4.00           1.0           0.0           0.0           0.0
3      1  640.0  3.19           0.0           0.0           0.0           1.0
4      0  520.0  2.93           0.0           0.0           0.0           1.0


In [8]:
prestige1_crosstab = pd.crosstab(index=handCalc['admit'],
                                columns=handCalc['prestige_1.0'])
prestige1_crosstab

prestige_1.0  0.0  1.0
admit                 
0             243   28
1              93   33

In [76]:
#crosstab prestige 1 admission 
#frequency table cutting prestige and whether or not someone was admitted

#### 3.1 Use the cross tab above to calculate the odds of being admitted to grad school if you attended a #1 ranked college

In [9]:
#Prestige 1.0 Odds

33.0/28.0

1.1785714285714286

#### 3.2 Now calculate the odds of admission if you did not attend a #1 ranked college

In [10]:
#Prestige 2,3,4 Odds

93.0/243.0

0.38271604938271603

#### 3.3 Calculate the odds ratio

In [11]:
1.178/0.382

3.083769633507853

#### 3.4 Write this finding in a sentence: 

Answer: You are 3x more likely to be admitted if you attended a prestige 1 school

#### 3.5 Print the cross tab for prestige_4

In [9]:
prestige4_crosstab = pd.crosstab(index=handCalc['admit'],
                            columns=handCalc['prestige_4.0'])
prestige4_crosstab

prestige_4.0  0.0  1.0
admit                 
0             216   55
1             114   12

#### 3.6 Calculate the OR 

In [13]:
#Prestige 4.0 Odds

12.0/55.0

0.21818181818181817

#### 3.7 Write this finding in a sentence

Answer: The odds of being admitted if you attended a Prestige 4 school is 5x less likely than attending a Prestige 1 school. 1:0.2 odds.

## Part 4. Analysis

In [10]:
# create a clean data frame for the regression

cols_to_keep = ['admit', 'gre', 'gpa']
handCalc = df[cols_to_keep].join(prestige_dummy.ix[:, 'prestige_2':])
print handCalc.head()

   admit    gre   gpa  prestige_2.0  prestige_3.0  prestige_4.0
0      0  380.0  3.61           0.0           1.0           0.0
1      1  660.0  3.67           0.0           1.0           0.0
2      1  800.0  4.00           0.0           0.0           0.0
3      1  640.0  3.19           0.0           0.0           1.0
4      0  520.0  2.93           0.0           0.0           1.0


We're going to add a constant term for our Logistic Regression. The statsmodels function we're going to be using requires that intercepts/constants are specified explicitly.

In [11]:
# manually add the intercept
handCalc['intercept'] = 1.0

#### 4.1 Set the covariates to a variable called train_cols

In [12]:
train_cols = handCalc.columns[1:]
logit = sm.Logit(handCalc['admit'], handCalc[train_cols])
result = logit.fit()

Optimization terminated successfully.
         Current function value: 0.573854
         Iterations 6


#### 4.2 Fit the model

In [13]:
print np.exp(result.params)

gre             1.002221
gpa             2.180027
prestige_2.0    0.506548
prestige_3.0    0.262192
prestige_4.0    0.211525
intercept       0.020716
dtype: float64


#### 4.3 Print the summary results

In [14]:
print result.summary()

                           Logit Regression Results                           
Dep. Variable:                  admit   No. Observations:                  397
Model:                          Logit   Df Residuals:                      391
Method:                           MLE   Df Model:                            5
Date:                Thu, 15 Dec 2016   Pseudo R-squ.:                 0.08166
Time:                        21:07:44   Log-Likelihood:                -227.82
converged:                       True   LL-Null:                       -248.08
                                        LLR p-value:                 1.176e-07
                   coef    std err          z      P>|z|      [95.0% Conf. Int.]
--------------------------------------------------------------------------------
gre              0.0022      0.001      2.028      0.043      7.44e-05     0.004
gpa              0.7793      0.333      2.344      0.019         0.128     1.431
prestige_2.0    -0.6801      0.317     -2.14

#### 4.4 Calculate the odds ratios of the coeffiencents and their 95% CI intervals

hint 1: np.exp(X)

hint 2: conf['OR'] = params
        
           conf.columns = ['2.5%', '97.5%', 'OR']

In [15]:
params = result.params
conf = result.conf_int()
conf['OR'] = params
conf.columns = ['2.5%', '97.5%', 'OR']
print np.exp(conf)

                  2.5%     97.5%        OR
gre           1.000074  1.004372  1.002221
gpa           1.136120  4.183113  2.180027
prestige_2.0  0.272168  0.942767  0.506548
prestige_3.0  0.133377  0.515419  0.262192
prestige_4.0  0.093329  0.479411  0.211525
intercept     0.002207  0.194440  0.020716


#### 4.5 Interpret the OR of Prestige_2

Answer: The odds of being admitted decreases by half if the school prestige is 2 so the odds are 2:1

#### 4.6 Interpret the OR of GPA

Answer: The odds of being admitted is 2x as likely the higher your GPA.

## Part 5: Predicted probablities


As a way of evaluating our classifier, we're going to recreate the dataset with every logical combination of input values. This will allow us to see how the predicted probability of admission increases/decreases across different variables. First we're going to generate the combinations using a helper function called cartesian (above).

We're going to use np.linspace to create a range of values for "gre" and "gpa". This creates a range of linearly spaced values from a specified min and maximum value--in our case just the min/max observed values.

In [16]:
def cartesian(arrays, out=None):
    """
    Generate a cartesian product of input arrays.
    Parameters
    ----------
    arrays : list of array-like
        1-D arrays to form the cartesian product of.
    out : ndarray
        Array to place the cartesian product in.
    Returns
    -------
    out : ndarray
        2-D array of shape (M, len(arrays)) containing cartesian products
        formed of input arrays.
    Examples
    --------
    >>> cartesian(([1, 2, 3], [4, 5], [6, 7]))
    array([[1, 4, 6],
           [1, 4, 7],
           [1, 5, 6],
           [1, 5, 7],
           [2, 4, 6],
           [2, 4, 7],
           [2, 5, 6],
           [2, 5, 7],
           [3, 4, 6],
           [3, 4, 7],
           [3, 5, 6],
           [3, 5, 7]])
    """

    arrays = [np.asarray(x) for x in arrays]
    dtype = arrays[0].dtype

    n = np.prod([x.size for x in arrays])
    if out is None:
        out = np.zeros([n, len(arrays)], dtype=dtype)

    m = n / arrays[0].size
    out[:,0] = np.repeat(arrays[0], m)
    if arrays[1:]:
        cartesian(arrays[1:], out=out[0:m,1:])
        for j in xrange(1, arrays[0].size):
            out[j*m:(j+1)*m,1:] = out[0:m,1:]
    return out

In [17]:
# instead of generating all possible values of GRE and GPA, we're going
# to use an evenly spaced range of 10 values from the min to the max 
gres = np.linspace(handCalc['gre'].min(), handCalc['gre'].max(), 10)
print gres
# array([ 220.        ,  284.44444444,  348.88888889,  413.33333333,
#         477.77777778,  542.22222222,  606.66666667,  671.11111111,
#         735.55555556,  800.        ])
gpas = np.linspace(handCalc['gpa'].min(), handCalc['gpa'].max(), 10)
print gpas
# array([ 2.26      ,  2.45333333,  2.64666667,  2.84      ,  3.03333333,
#         3.22666667,  3.42      ,  3.61333333,  3.80666667,  4.        ])


# enumerate all possibilities
combos = pd.DataFrame(cartesian([gres, gpas, [1, 2, 3, 4], [1.]]))

[ 220.          284.44444444  348.88888889  413.33333333  477.77777778
  542.22222222  606.66666667  671.11111111  735.55555556  800.        ]
[ 2.26        2.45333333  2.64666667  2.84        3.03333333  3.22666667
  3.42        3.61333333  3.80666667  4.        ]


#### 5.1 Recreate the dummy variables

In [24]:
# recreate the dummy variables
# keep only what we need for making predictions

gre_dummy = pd.get_dummies(handCalc.gre, prefix='gre')

gre_dummy.head()

gre_220.0  gre_300.0  gre_340.0  gre_360.0  gre_380.0  gre_400.0  \
0        0.0        0.0        0.0        0.0        1.0        0.0   
1        0.0        0.0        0.0        0.0        0.0        0.0   
2        0.0        0.0        0.0        0.0        0.0        0.0   
3        0.0        0.0        0.0        0.0        0.0        0.0   
4        0.0        0.0        0.0        0.0        0.0        0.0   

   gre_420.0  gre_440.0  gre_460.0  gre_480.0    ...      gre_620.0  \
0        0.0        0.0        0.0        0.0    ...            0.0   
1        0.0        0.0        0.0        0.0    ...            0.0   
2        0.0        0.0        0.0        0.0    ...            0.0   
3        0.0        0.0        0.0        0.0    ...            0.0   
4        0.0        0.0        0.0        0.0    ...            0.0   

   gre_640.0  gre_660.0  gre_680.0  gre_700.0  gre_720.0  gre_740.0  \
0        0.0        0.0        0.0        0.0        0.0        0.0   
1        0.0        1.0        0.0        0.0        0.0        0.0   
2        0.0        0.0        0.0        0.0        0.0        0.0   
3        1.0        0.0        0.0        0.0        0.0        0.0   
4        0.0        0.0        0.0        0.0        0.0        0.0   

   gre_760.0  gre_780.0  gre_800.0  
0        0.0        0.0        0.0  
1        0.0        0.0        0.0  
2        0.0        0.0        1.0  
3        0.0        0.0        0.0  
4        0.0        0.0        0.0  

[5 rows x 26 columns]

In [25]:
gpa_dummy = pd.get_dummies(handCalc.gpa, prefix='gpa')

gpa_dummy.head()

gpa_2.26  gpa_2.42  gpa_2.48  gpa_2.52  gpa_2.55  gpa_2.56  gpa_2.62  \
0       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
1       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
2       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
3       0.0       0.0       0.0       0.0       0.0       0.0       0.0   
4       0.0       0.0       0.0       0.0       0.0       0.0       0.0   

   gpa_2.63  gpa_2.65  gpa_2.67   ...     gpa_3.9  gpa_3.91  gpa_3.92  \
0       0.0       0.0       0.0   ...         0.0       0.0       0.0   
1       0.0       0.0       0.0   ...         0.0       0.0       0.0   
2       0.0       0.0       0.0   ...         0.0       0.0       0.0   
3       0.0       0.0       0.0   ...         0.0       0.0       0.0   
4       0.0       0.0       0.0   ...         0.0       0.0       0.0   

   gpa_3.93  gpa_3.94  gpa_3.95  gpa_3.97  gpa_3.98  gpa_3.99  gpa_4.0  
0       0.0       0.0       0.0       0.0       0.0       0.0      0.0  
1       0.0       0.0       0.0       0.0       0.0       0.0      0.0  
2       0.0       0.0       0.0       0.0       0.0       0.0      1.0  
3       0.0       0.0       0.0       0.0       0.0       0.0      0.0  
4       0.0       0.0       0.0       0.0       0.0       0.0      0.0  

[5 rows x 131 columns]

In [27]:
prestige_dummy.head()

prestige_1.0  prestige_2.0  prestige_3.0  prestige_4.0
0           0.0           0.0           1.0           0.0
1           0.0           0.0           1.0           0.0
2           1.0           0.0           0.0           0.0
3           0.0           0.0           0.0           1.0
4           0.0           0.0           0.0           1.0

#### 5.2 Make predictions on the enumerated dataset

In [30]:
cols_to_keep = ['gre', 'gpa', 'prestige', 'intercept']
combos = combos[cols_to_keep].join(dummy_ranks.ix[:, 'prestige_2':])
combos['admit'] = result.predict(combos[train_cols])

print combos.head()

KeyError: "Index([u'prestige_2.0', u'prestige_3.0', u'prestige_4.0'], dtype='object') not in index"

#### 5.3 Interpret findings for the last 4 observations

Answer: 

## Bonus

Plot the probability of being admitted into graduate school, stratified by GPA and GRE score.